[application]

[web.app]

# HTML title tag content
title = "apl-formatter"

[web.resource]

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
